### PR TITLE
Added Project in WPF

### PR DESCRIPTION
**Pull request by M1XT3NZ**
Basically just made the same program in WPF(WPF is way more expandable than Winforms is)

Anyway, there might be some leftover shit code that still needs to be deleted, and so on.

This is definitely not ready to be merged but I just wanted to show that I'm working on something. 

(also I did not have access to the updater.exe so that is temporarily removed) (tbh now that I realize that I just could've got it really easily makes me wanna die inside)

### CODE REVIEW

**Comment by WilliamRagstad** [comment]
Wow! I'm really impressed with the amount of job you've done so far!
I'm definitely interested in your project and will take a closer look at it later today.
Thanks for sharing👌

**Comment by M1XT3NZ** [comment]
It’s not 100% working yet.
(I think can’t remember)
Small things that may need to be changed or fixed.

Probably looked over a lot of things and a lot of left over code.
(It’s 99% your repository code anyway)

Anyway I only did the ui anyway.
If you find anything please let me know. :)

**Comment by M1XT3NZ** [comment]
Should work to 99.99% now. :P
tbh it doesn't matter if you keep the winforms or wpf version or both and just give one of them as a release if at all, 
Winforms files are still not up to date with the wpf version but I will fix that tomorrow if I don't forget. Have a great day :)

**Comment by M1XT3NZ** [comment]
as of now This should not be merged...
i found a few bugs that i didnt find while testing.. Gotta love it.

**Pull request closed without merging**
